services:
  mysql:
    image: mysql:8
    restart: unless-stopped
    hostname: mysql
    networks:
      - discord-tickets
    volumes:
      - tickets-mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: tickets
      MYSQL_PASSWORD: insecure # change this to a secure password
      MYSQL_ROOT_PASSWORD: insecure # change this to a (different) secure password
      MYSQL_USER: tickets

  bot:
    image: "ghcr.io/discord-tickets/bot:main"
    depends_on:
      - mysql
    restart: unless-stopped
    hostname: bot
    networks:
      - discord-tickets
    ports:
      - 8169:8169
    volumes:
      - tickets-bot:/home/container/user
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    tty: true
    stdin_open: true
    environment:
      DB_CONNECTION_URL: mysql://tickets:insecure@mysql/tickets # change `insecure` to the MYSQL_PASSWORD you set above
      DISCORD_SECRET: gYOaQrrb8Qni3qRibYT_q-iE3Zwhwg4F
      DISCORD_TOKEN: MTI0MjEzNjQyOTk0NjIxMjQ4Mg.G1KCbj.rrt5lXrUD4FIDhvRiWPZiYz9AfD94ljpUnzbLw
      ENCRYPTION_KEY: bddb0d3654d741ebc83b39a2c648b67dfa10d53b79da3a15
      DB_PROVIDER: mysql
      HTTP_EXTERNAL: http://127.0.0.1:8169 # change this to your server's external IP (or domain)
      HTTP_HOST: 0.0.0.0
      HTTP_INTERNAL:
      HTTP_PORT: 8169
      HTTP_TRUST_PROXY: "false" # set to true if you're using a reverse proxy
      INVALIDATE_TOKENS:
      OVERRIDE_ARCHIVE: null
      PUBLIC_BOT: "false"
      PUBLISH_COMMANDS: "false"
      SUPER: 319467558166069248 # optionally add `,youruseridhere`

networks:
  discord-tickets:

volumes:
  tickets-mysql:
  tickets-bot:
